---
abstract: 'Implements an FTP client POE Component'
author:
  - 'Michael Ching <michaelc@wush.net>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-FTP
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Carp: 0
  Exporter: 0
  POE: 0.38
  POE::Driver::SysRW: 0
  POE::Filter::Line: 0
  POE::Filter::Stream: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  Socket: 0
  perl: 5.6.0
  vars: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.22
